Repository ZhuravlevE/TeamDev, pull requests merged in 2023-05, with the labels that each got.

#22 Feature/new scripts
  Assets/Scripts/PhantomGreen.cs
  Assets/Scripts/PhantomGreen.cs.meta
  Assets/Scripts/PhantomRed.cs
  Assets/Scripts/PhantomRed.cs.meta
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerMovement.cs.meta
Labels: code, mechanics

#30 Добавил файлы навигации для ресурсов
  Assets/Animations.meta
  Assets/Audio.meta
  Assets/Resources.meta
  Assets/Scenes.meta
  Assets/Scripts.meta
  Assets/Tests.meta
Labels: code

#31 Добавил удаленную документацию
  Assets/Scripts/Key.cs
  Assets/Scripts/Objectives.cs
  Assets/Scripts/PhantomGreen.cs
  Assets/Scripts/PhantomRed.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerSpawn.cs
  Assets/Scripts/SpawnPhantom.cs
Labels: documentation, invalid, code
